DROP TABLE IF EXISTS USERS_ZAHSHBSH;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS PRIV_USERS;

CREATE TABLE USERS_ZAHSHBSH(
    id SERIAL PRIMARY KEY,
    username varchar(255) UNIQUE NOT NULL,
    password varchar(255) UNIQUE NOT NULL,
    is_admin INTEGER DEFAULT 0
);

CREATE TABLE PRIV_USERS(
    id SERIAL PRIMARY KEY,
    username varchar(255) UNIQUE NOT NULL,
    password varchar(255) UNIQUE NOT NULL,
    is_admin INTEGER DEFAULT 1
);

CREATE TABLE PRODUCTS(
    id SERIAL PRIMARY KEY,
    description varchar(255) UNIQUE NOT NULL,
    price varchar(255) UNIQUE NOT NULL
);